### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by shcheran-lidar** [SmartForest-no/SegmentAnyTree#12]
bash run_docker_locally.sh
Removing existing container test_e2e_instance
test_e2e_instance
[+] Building 1.7s (25/25) FINISHED                                                                                                                       docker:default
 => [internal] load build definition from Dockerfile                                                                                                               0.0s
 => => transferring dockerfile: 6.86kB                                                                                                                             0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)                                                                                     0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04                                                                             0.7s
 => [internal] load .dockerignore                                                                                                                                  0.0s
 => => transferring context: 889B                                                                                                                                  0.0s
 => [internal] load build context                                                                                                                                  0.0s
 => => transferring context: 31.13kB                                                                                                                               0.0s
 => [builder  1/12] FROM docker.io/nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04@sha256:83e4b2841034cdf45ea5b9a5b472eb2c07b1b23d4836d32666a881db29a8dceb             0.0s
 => CACHED [builder  2/12] RUN ln -fs /usr/share/zoneinfo/Europe/Oslo /etc/localtime                                                                               0.0s
 => CACHED [builder  3/12] RUN apt-get update && apt-get install -y --no-install-recommends     build-essential     git     language-pack-en-base     openssh-ser  0.0s
 => CACHED [builder  4/12] RUN python3.8 -m pip install --no-cache-dir --upgrade     autopep8==1.5.7     doc8==0.8.1     docutils==0.17.1     ipython==7.27.0      0.0s
 => CACHED [builder  5/12] RUN python3.8 -m pip install --no-cache-dir     torch==1.9.0+cu111     torchvision==0.10.0+cu111     torchaudio==0.9.0     -f https://  0.0s
 => CACHED [builder  6/12] RUN python3.8 -m pip install --no-cache-dir     torch-scatter==2.0.8     torch-sparse==0.6.12     torch-cluster==1.5.9     torch-splin  0.0s
 => CACHED [builder  7/12] RUN TORCH_CUDA_ARCH_LIST=6.0;7.0;7.5;8.0;8.6 python3.8 -m pip install --no-cache-dir     git+https://github.com/NVIDIA/MinkowskiEngine  0.0s
 => CACHED [builder  8/12] RUN TORCH_CUDA_ARCH_LIST=6.0;7.0;7.5;8.0;8.6 FORCE_CUDA=1 python3.8 -m pip install --no-cache-dir     git+https://github.com/mit-han-l  0.0s
 => CACHED [builder  9/12] RUN TORCH_CUDA_ARCH_LIST=6.0;7.0;7.5;8.0;8.6 FORCE_CUDA=1 python3.8 -m pip install --no-cache-dir     torch-points-kernels==0.7.0       0.0s
 => CACHED [builder 10/12] RUN python3.8 -m pip install cython==0.29.37                                                                                            0.0s
 => CACHED [builder 11/12] RUN wget https://github.com/scikit-learn-contrib/hdbscan/archive/refs/tags/0.8.29.zip &&     unzip 0.8.29.zip &&     rm 0.8.29.zip &&   0.0s
 => CACHED [builder 12/12] RUN apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* &&     find /usr/local -depth     (       ( -type d -a -name te  0.0s
 => CACHED [final  3/10] COPY --from=builder /usr/local/bin /usr/local/bin                                                                                         0.0s
 => CACHED [final  4/10] COPY --from=builder /usr/local/lib /usr/local/lib                                                                                         0.0s
 => CACHED [final  5/10] COPY --from=builder /usr/local/include /usr/local/include                                                                                 0.0s
 => CACHED [final  6/10] RUN apt-get update && apt-get install -y --no-install-recommends     libopenblas-base     python3.8     python3.8-dev     python3-pip     0.0s
 => CACHED [final  7/10] RUN python3.8 -m pip install --no-cache-dir     numba==0.57.1     numpy==1.24.4     jaklas     dask==2021.8.1     pykdtree==1.3.7.post0   0.0s
 => CACHED [final  8/10] RUN mkdir -p /home/datascience                                                                                                            0.0s
 => [final  9/10] COPY . /home/nibio/mutable-outside-world                                                                                                         0.3s
 => [final 10/10] WORKDIR /home/nibio/mutable-outside-world                                                                                                        0.0s
 => exporting to image                                                                                                                                             0.6s
 => => exporting layers                                                                                                                                            0.6s
 => => writing image sha256:4edf17e7c99e4b7c72a449194e78c745bb2497c821819a1b8eb9961a4efddbb2                                                                       0.0s
 => => naming to docker.io/nibio/e2e-instance                                                                                                                      0.0s

 1 warning found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
Running the container
Input directory: /home/datascience/tmp_in_folder
Output directory: /home/datascience/tmp_out_folder
Script directory: /home/nibio/mutable-outside-world
Renamed: /home/datascience/tmp_out_folder/input_data/andy_high_vegetation_subset.las to /home/datascience/tmp_out_folder/input_data/andy_high_vegetation_subset.las
Processing 1 files...
Processing in utm2local: /home/datascience/tmp_out_folder/input_data/andy_high_vegetation_subset.las
Saving min values to: /home/datascience/tmp_out_folder/utm2local/andy_high_vegetation_subset_out_min_values.json
Output files are saved in: /home/datascience/tmp_out_folder/utm2local
Clearing: /home/datascience/tmp_out_folder/utm2local/treeinsfused/processed_0.2_test
Path does not exist: /home/datascience/tmp_out_folder/utm2local/treeinsfused/processed_0.2_test
/usr/local/lib/python3.8/dist-packages/wandb/__init__.py:998: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if name is None and resume is not "must":
/usr/local/lib/python3.8/dist-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.2.0)/charset_normalizer (2.0.6) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
/usr/local/lib/python3.8/dist-packages/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
[2024-11-28 07:56:30,150][torch_points3d.trainer][INFO] - DEVICE : cuda
/home/nibio/mutable-outside-world/model_file
PointGroup-PAPER
False
True
{'num_workers': 0, 'batch_size': 1, 'cuda': 0, 'weight_name': 'latest', 'enable_cudnn': True, 'checkpoint_dir': '/home/nibio/mutable-outside-world/model_file', 'model_name': 'PointGroup-PAPER', 'precompute_multi_scale': True, 'enable_dropout': False, 'voting_runs': 1, 'data': {'fold': ['/home/datascience/tmp_out_folder/utm2local/andy_high_vegetation_subset_out.ply']}, 'tracker_options': {'full_res': True, 'make_submission': True, 'ply_output': 'maciej_eval.ply'}, 'visualization': {'activate': True, 'format': 'pointcloud', 'num_samples_per_epoch': -1, 'deterministic': True, 'saved_keys': {'pos': [['x', 'float'], ['y', 'float'], ['z', 'float']], 'y': [['l', 'float']], 'pred': [['p', 'float']]}}, 'training': {'num_workers': 0, 'batch_size': 1, 'cuda': 0, 'weight_name': 'latest', 'enable_cudnn': True, 'checkpoint_dir': '/home/nibio/mutable-outside-world/model_file', 'model_name': 'PointGroup-PAPER', 'precompute_multi_scale': True, 'enable_dropout': False, 'voting_runs': 1, 'data': {'fold': ['/home/datascience/tmp_out_folder/utm2local/andy_high_vegetation_subset_out.ply']}, 'tracker_options': {'full_res': True, 'make_submission': True, 'ply_output': 'maciej_eval.ply'}, 'visualization': {'activate': True, 'format': 'pointcloud', 'num_samples_per_epoch': -1, 'deterministic': True, 'saved_keys': {'pos': [['x', 'float'], ['y', 'float'], ['z', 'float']], 'y': [['l', 'float']], 'pred': [['p', 'float']]}}}}
[2024-11-28 07:56:30,155][torch_points3d.metrics.model_checkpoint][INFO] - Loading checkpoint from /home/nibio/mutable-outside-world/model_file/PointGroup-PAPER.pt
/home/nibio/mutable-outside-world/model_file/PointGroup-PAPER.pt
Traceback (most recent call last):
  File "eval.py", line 13, in main
    trainer = Trainer(cfg)
  File "/home/nibio/mutable-outside-world/torch_points3d/trainer.py", line 48, in __init__
    self._initialize_trainer()
  File "/home/nibio/mutable-outside-world/torch_points3d/trainer.py", line 80, in _initialize_trainer
    self._checkpoint: ModelCheckpoint = ModelCheckpoint(
  File "/home/nibio/mutable-outside-world/torch_points3d/metrics/model_checkpoint.py", line 179, in __init__
    self._checkpoint = Checkpoint.load(load_dir, check_name, run_config=rc, strict=strict, resume=resume)
  File "/home/nibio/mutable-outside-world/torch_points3d/metrics/model_checkpoint.py", line 86, in load
    objects = torch.load(checkpoint_file, map_location="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by shcheran-lidar** [comment]
Dear authors! Thank you for sharing your exciting project with the audience! Everything went well once I downloaded the model .PointGroup-PAPER.pt from drive. Also, the issue with .thing_class (which is mentioned in the first re-open issue) got solved with the patch #9. 

So, this issue can be closed. However, I could not figure out where the resulting .las (with panoptic segmentation) got saved to.
Thanks in advance for aiding me!

**Comment by shcheran-lidar** [comment]
An update: I located the results, but instance segmentation does not seem to work well with the palm trees. It mostly detects the middle parts as a tree. I will make more runs on boreal forest cases. Thank you anyways, it is a great tool for forestry automation.

**Comment by VGrondin** [comment]
> Dear authors,
> 
> Thank you for sharing your exciting project with the community! Everything worked smoothly once I downloaded the model PointGroup-PAPER.pt from the drive. 

Can you explain a bit more, I am facing the same issue

```
[2024-12-31 00:52:52,884][torch_points3d.trainer][INFO] - DEVICE : cpu
[2024-12-31 00:52:52,886][torch_points3d.metrics.model_checkpoint][INFO] - Loading checkpoint from /home/nibio/mutable-outside-world/model_file/PointGroup-PAPER.pt
Traceback (most recent call last):
  File "eval.py", line 13, in main
    trainer = Trainer(cfg)
  File "/home/nibio/mutable-outside-world/torch_points3d/trainer.py", line 48, in __init__
    self._initialize_trainer()
  File "/home/nibio/mutable-outside-world/torch_points3d/trainer.py", line 80, in _initialize_trainer
    self._checkpoint: ModelCheckpoint = ModelCheckpoint(
  File "/home/nibio/mutable-outside-world/torch_points3d/metrics/model_checkpoint.py", line 173, in __init__
    self._checkpoint = Checkpoint.load(load_dir, check_name, run_config=rc, strict=strict, resume=resume)
  File "/home/nibio/mutable-outside-world/torch_points3d/metrics/model_checkpoint.py", line 85, in load
    objects = torch.load(checkpoint_file, map_location="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

Although there is a checkpoint file in 

```
root@079738ab7c65:/home/nibio/mutable-outside-world# cd model_file/
root@079738ab7c65:/home/nibio/mutable-outside-world/model_file# ls
PointGroup-PAPER.pt
```

**Comment by CiSong10** [comment]
Hi, I'm facing the same issue. @shcheran-lidar could you share where you found the results?
