### ISSUE TITLE
About the enviroment

### ISSUE THREAD

**Issue by BruceWayne233** [SmartForest-no/SegmentAnyTree#2]
Hi, thanks for your work, it is very inspiring to me. Because I am renting a cloud server to run the code, it is not convenient to use docker. I wonder if I can use FORAINet's environment to run it?

**Comment by BruceWayne233** [comment]
Thank you. I would also like to ask about the pre-trained weights. Where can I download the pre-trained weights?

**Comment by BruceWayne233** [comment]
Sorry to bother you in your busy schedule, is this the pre-trained weight of SegmentAnyTree? [https://github.com/SmartForest-no/SegmentAnyTree/blob/main/model_file/PointGroup-PAPER.pt](url).

**Comment by maciekwielgosz** [comment]
Yes, But you need to use the whole folder : https://github.com/SmartForest-no/SegmentAnyTree/tree/main/model_file since it contains other files which are necessary for loading the model.
