### ISSUE TITLE
issue with run_oracle_pipeline.sh for docker environment

### ISSUE THREAD

**Issue by DonMaEn** [SmartForest-no/SegmentAnyTree#3]
By default the run_oracle_pipeline.sh script has a DEBUG environment variable set to false. It appears that this script is only designed to run using the docker environment when DEBUG is set to true. If what I am saying is correct, I suggest either setting this variable based on if the user is running in a container, or changing the default value of this variable.

**Comment by maciekwielgosz** [comment]
The default value of DEBUG was changed to true.
