### ISSUE TITLE
Missing large_PC_predict.sh script

### ISSUE THREAD

**Issue by DonMaEn** [SmartForest-no/SegmentAnyTree#4]
the `run_inference.sh` script, which appears to be one of the main scripts used in the inference pipeline, refers to a script called `large_PC_predict.sh`. This script does not exist in the repo or in the docker container. Was this a script that should have been included with the repo but was accidentally left out?

**Comment by maciekwielgosz** [comment]
The `run_inference.sh` file has been  updated and `large_PC_predict.sh` is not needed.
