### ISSUE TITLE
Git LFS error

### ISSUE THREAD

**Issue by julesmorel** [SmartForest-no/SegmentAnyTree#8]
I am receiving the following error when trying to checkout the code:

`Downloading model_file/PointGroup-PAPER.pt (666 MB)
Error downloading object: model_file/PointGroup-PAPER.pt (0b4d74b): Smudge error: Error downloading model_file/PointGroup-PAPER.pt (0b4d74b4644e37a16f59008ad0f5c62894fc4d2d906f3abd803bbfc5b5dd803a): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

Is this a problem if we run the code in the docker?

**Comment by maciekwielgosz** [comment]
This is not related to docker.
Please find the model also here : https://drive.google.com/file/d/1mRS44vrZ8q9WusGE0PRWzcB_9O5TpZpS/view?usp=drive_link
